// <auto-generated />
using CIDM_3312_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM_3312_Final_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505214702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReputationRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearFounded")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmmoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WeaponID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Weapon", b =>
                {
                    b.HasOne("CIDM_3312_Final_Project.Models.Manufacturer", "Manufacturer")
                        .WithMany("Weapons")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Manufacturer", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
