// <auto-generated />
using CIDM_3312_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM_3312_Final_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505215231_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReputationRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearFounded")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerID = 1,
                            Faction = "UNSC",
                            Name = "Misriah Armory",
                            PlanetOfOrigin = "Earth",
                            ReputationRating = 4.5m,
                            YearFounded = 2160
                        },
                        new
                        {
                            ManufacturerID = 2,
                            Faction = "Covenant",
                            Name = "Assembly Forges",
                            PlanetOfOrigin = "High Charity",
                            ReputationRating = 4.8m,
                            YearFounded = 2100
                        },
                        new
                        {
                            ManufacturerID = 3,
                            Faction = "Brutes",
                            Name = "Weapon Systems Tech Co.",
                            PlanetOfOrigin = "Doisac",
                            ReputationRating = 4.2m,
                            YearFounded = 2200
                        });
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmmoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WeaponID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            WeaponID = 1,
                            AmmoType = "7.62mm",
                            DamageRating = 300,
                            ManufacturerID = 1,
                            Name = "Assault Rifle",
                            Price = 1500m,
                            StockQuantity = 50,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 2,
                            AmmoType = "12.7mm",
                            DamageRating = 200,
                            ManufacturerID = 1,
                            Name = "Magnum",
                            Price = 800m,
                            StockQuantity = 75,
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            WeaponID = 3,
                            AmmoType = "8 gauge",
                            DamageRating = 450,
                            ManufacturerID = 1,
                            Name = "Shotgun",
                            Price = 2200m,
                            StockQuantity = 25,
                            WeaponType = "Shotgun"
                        },
                        new
                        {
                            WeaponID = 4,
                            AmmoType = "14.5mm",
                            DamageRating = 750,
                            ManufacturerID = 1,
                            Name = "Sniper Rifle",
                            Price = 5000m,
                            StockQuantity = 15,
                            WeaponType = "Sniper"
                        },
                        new
                        {
                            WeaponID = 5,
                            AmmoType = "Rockets",
                            DamageRating = 850,
                            ManufacturerID = 1,
                            Name = "Rocket Launcher",
                            Price = 7000m,
                            StockQuantity = 8,
                            WeaponType = "Launcher"
                        },
                        new
                        {
                            WeaponID = 6,
                            AmmoType = "Plasma",
                            DamageRating = 220,
                            ManufacturerID = 2,
                            Name = "Plasma Pistol",
                            Price = 1200m,
                            StockQuantity = 40,
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            WeaponID = 7,
                            AmmoType = "Plasma",
                            DamageRating = 300,
                            ManufacturerID = 2,
                            Name = "Plasma Rifle",
                            Price = 1600m,
                            StockQuantity = 40,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 8,
                            AmmoType = "Plasma",
                            DamageRating = 350,
                            ManufacturerID = 2,
                            Name = "Carbine",
                            Price = 1700m,
                            StockQuantity = 30,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 9,
                            AmmoType = "Crystal",
                            DamageRating = 350,
                            ManufacturerID = 2,
                            Name = "Needler",
                            Price = 2000m,
                            StockQuantity = 30,
                            WeaponType = "SMG"
                        },
                        new
                        {
                            WeaponID = 10,
                            AmmoType = "Energy",
                            DamageRating = 600,
                            ManufacturerID = 2,
                            Name = "Energy Sword",
                            Price = 5000m,
                            StockQuantity = 20,
                            WeaponType = "Sword"
                        },
                        new
                        {
                            WeaponID = 11,
                            AmmoType = "Explosive Shells",
                            DamageRating = 700,
                            ManufacturerID = 3,
                            Name = "Brute Shot",
                            Price = 5000m,
                            StockQuantity = 11,
                            WeaponType = "Launcher"
                        },
                        new
                        {
                            WeaponID = 12,
                            AmmoType = "Gravity",
                            DamageRating = 800,
                            ManufacturerID = 3,
                            Name = "Gravity Hammer",
                            Price = 6000m,
                            StockQuantity = 10,
                            WeaponType = "Melee"
                        },
                        new
                        {
                            WeaponID = 13,
                            AmmoType = "Metal Spikes",
                            DamageRating = 320,
                            ManufacturerID = 3,
                            Name = "Spiker",
                            Price = 1800m,
                            StockQuantity = 35,
                            WeaponType = "SMG"
                        },
                        new
                        {
                            WeaponID = 14,
                            AmmoType = "Particle Beam",
                            DamageRating = 750,
                            ManufacturerID = 2,
                            Name = "Beam Rifle",
                            Price = 6000m,
                            StockQuantity = 12,
                            WeaponType = "Sniper"
                        },
                        new
                        {
                            WeaponID = 15,
                            AmmoType = "Fuel Rod",
                            DamageRating = 850,
                            ManufacturerID = 2,
                            Name = "Fuel Rod Gun",
                            Price = 6800m,
                            StockQuantity = 9,
                            WeaponType = "Launcher"
                        },
                        new
                        {
                            WeaponID = 16,
                            AmmoType = "5x23mm",
                            DamageRating = 300,
                            ManufacturerID = 1,
                            Name = "SMG",
                            Price = 1000m,
                            StockQuantity = 50,
                            WeaponType = "SMG"
                        },
                        new
                        {
                            WeaponID = 17,
                            AmmoType = "9.5mm",
                            DamageRating = 400,
                            ManufacturerID = 1,
                            Name = "Battle Rifle",
                            Price = 1800m,
                            StockQuantity = 45,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 18,
                            AmmoType = "Energy",
                            DamageRating = 500,
                            ManufacturerID = 2,
                            Name = "Sentinel Beam",
                            Price = 2500m,
                            StockQuantity = 15,
                            WeaponType = "Beam"
                        },
                        new
                        {
                            WeaponID = 19,
                            AmmoType = "8 gauge",
                            DamageRating = 460,
                            ManufacturerID = 1,
                            Name = "Tactical Shotgun",
                            Price = 2300m,
                            StockQuantity = 25,
                            WeaponType = "Shotgun"
                        },
                        new
                        {
                            WeaponID = 20,
                            AmmoType = "7.62mm",
                            DamageRating = 410,
                            ManufacturerID = 1,
                            Name = "DMR",
                            Price = 1900m,
                            StockQuantity = 40,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 21,
                            AmmoType = "Crystal",
                            DamageRating = 370,
                            ManufacturerID = 2,
                            Name = "Needle Rifle",
                            Price = 2100m,
                            StockQuantity = 25,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 22,
                            AmmoType = "Plasma",
                            DamageRating = 880,
                            ManufacturerID = 2,
                            Name = "Plasma Launcher",
                            Price = 7000m,
                            StockQuantity = 8,
                            WeaponType = "Launcher"
                        },
                        new
                        {
                            WeaponID = 23,
                            AmmoType = "Concussive Blast",
                            DamageRating = 780,
                            ManufacturerID = 3,
                            Name = "Concussion Rifle",
                            Price = 5200m,
                            StockQuantity = 10,
                            WeaponType = "Launcher"
                        },
                        new
                        {
                            WeaponID = 24,
                            AmmoType = "Plasma",
                            DamageRating = 310,
                            ManufacturerID = 2,
                            Name = "Plasma Repeater",
                            Price = 1650m,
                            StockQuantity = 37,
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            WeaponID = 25,
                            AmmoType = "Shells",
                            DamageRating = 400,
                            ManufacturerID = 3,
                            Name = "Mauler",
                            Price = 2000m,
                            StockQuantity = 30,
                            WeaponType = "Shotgun"
                        });
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Weapon", b =>
                {
                    b.HasOne("CIDM_3312_Final_Project.Models.Manufacturer", "Manufacturer")
                        .WithMany("Weapons")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CIDM_3312_Final_Project.Models.Manufacturer", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
